backend:
  name: github
  repo: nowakdeclan-bit/codspace # 👈 This points to your club repo
  branch: main # Change to 'master' if your default branch is master

media_folder: "images" # Where images you upload via the CMS will go
public_folder: "/images"

collections:
  - name: "updates"
    label: "Club Updates"
    folder: "updates" # Where your written updates will be saved in GitHub
    create: true # Allows you to make new ones
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
